name: Unit Test

on: pull_request

jobs:
  build:
    name: Unit Test (${{ matrix.node-name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14', '16']
        include:
          - node-version: '14'
            node-name: 'LTS'
          - node-version: '16'
            node-name: 'Latest'
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.15.1
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
